### PR TITLE
Fixing setup install

### PR DESCRIPTION
**Pull request by ruffsl**
Currently, pip installs no code.
This fixes that, but you may want to restructure further.

### CODE REVIEW

**Comment by Keda87** [comment]
@ruffsl Hi, thanks for the PR.
Actually, I have no idea what should I restructure on this.
Any suggestion? I will merge this PR after your response.

**Comment by ruffsl** [comment]
I'm not sure what scaffolding structure you'd prefer, but I found these docs useful:
- http://python-packaging.readthedocs.io/en/latest/minimal.html
- http://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/creation.html

**Comment by Keda87** [comment]
@ruffsl I see, will consider to use those references. thank you!

**Comment by ruffsl** [comment]
You may also want to re-release you package version on PyPI for the fix to take effect with pip.

**Comment by Keda87** [comment]
@ruffsl Yes, will do and uploaded on pypi now

**Pull request merged**
